### ISSUE TITLE
optimization not working as expected

### ISSUE THREAD

**Issue by atiehmokhtary** [spatie/laravel-image-optimizer#11]
hello there, I am facing an issue. I am checking my site speed rank with google insights (https://developers.google.com/speed/pagespeed/insights/) and when I compare mine optimized imaged with the google optimized images, there are lots of difference. forexample my original image has 30kb, after optimizing with spatie package it got size 28kb, and google does the optimization on it and reduce the size to 10kb. how does the google do the optimization? how can I use this package to do the same as google?

**Comment by freekmurze** [comment]
It's easy to get lower sizes when you sacrifice a bit of quality. The [default configuration](https://github.com/spatie/laravel-image-optimizer/blob/master/config/image-optimizer.php) of this package will try to preserve quality as much as possible and only adds a little compression. 

Afaik Google doesn't document which parameters and tools it uses to achieve their results.
