### ISSUE TITLE
Not working on Windows 10 development system

### ISSUE THREAD

**Issue by sanjayojha** [spatie/laravel-image-optimizer#13]
I tried it on my local windows development machine and it didn't worked, I mean it didn't optimized the image.

**PHP Version: 7.1**
**OS: Windows 10**
**Note**: I am using WAMP

After installing via compser, I appended the `Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider::class,`  in providers array in config/app.php

also added in routeMiddleware, as below
```
// app/Http/Kernel.php
protected $routeMiddleware = [
   'optimizeImages' => \Spatie\LaravelImageOptimizer\Middlewares\OptimizeImages::class,
];
```

finally I added to the Route
`Route::post('post/create', 'BlogController@storePost')->name('post.store')->middleware('optimizeImages');`

But it didn't optimize the image. This route is called when the form is submitted.

**Comment by freekmurze** [comment]
I'm not a Windows user so can't help you there.

You could [active logging](https://github.com/spatie/laravel-image-optimizer/blob/master/config/image-optimizer.php#L50), run the optimizer and see if the log contains some entries that help you discover why it isn't working.

**Comment by sanjayojha** [comment]
Thank you, I just enabled the logging and check again, below is the error log i get

```
[2017-08-17 10:43:47] local.INFO: Start optimizing C:\Windows\Temp\phpE0C7.tmp  
[2017-08-17 10:43:47] local.INFO: Using optimizer: `Spatie\ImageOptimizer\Optimizers\Jpegoptim`  
[2017-08-17 10:43:47] local.INFO: Executing `'jpegoptim' --strip-all --all-progressive "C:\Windows\Temp\phpE0C7.tmp"`  
[2017-08-17 10:43:47] local.ERROR: Process errored with `''jpegoptim'' is not recognized as an internal or external command,
operable program or batch file.
`}  
[2017-08-17 10:44:14] local.INFO: Start optimizing C:\Windows\Temp\php4AEC.tmp  
[2017-08-17 10:44:14] local.INFO: Using optimizer: `Spatie\ImageOptimizer\Optimizers\Jpegoptim`  
[2017-08-17 10:44:14] local.INFO: Executing `'jpegoptim' --strip-all --all-progressive "C:\Windows\Temp\php4AEC.tmp"`  
[2017-08-17 10:44:14] local.ERROR: Process errored with `''jpegoptim'' is not recognized as an internal or external command,
operable program or batch file.
`}  

```
So, I guess -``''jpegoptim'' is not recognized as an internal or external command,
operable program or batch file.` is problem

**Comment by freekmurze** [comment]
Is that tool installed on your system? If it continues to give you troubles remove it from the config file and provide your own tool to optimize jpeg's. 

If there's anything for me to fix in the package itself, let me know.

**Comment by sanjayojha** [comment]
Thank you for reply. Actually I think `Jpegoptim`, `Pngquant`, `Optipng`  etc are not a part of windows, So according to me there is no way to make it work on windows unless there is an installer package for windows.
I will suggest you to confirm this from other sources and if confirmed mention this somewhere in your description.

**Comment by Neve12ende12** [comment]
@sanjayojha @freekmurze You can easily set this up to work on windows.  Note, I've only tested with Pngquant and Optiping so far.

1. Install Pngquant and Optiping binaries for Windows
2. Add the binaries to the Environment Path
3. Restart your server so the path variable is updated
4. Modify BaseOptimizer.php:Line 41 from (this modification will be overwrote if composer updates the package)

    return "'{$this->binaryName}' {$optionString} ".escapeshellarg($this->imagePath);
    
    to
    
    return "{$this->binaryName} {$optionString} ".escapeshellarg($this->imagePath);

5. Enjoy optimized images
