### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalThrowableError]   Class 'Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider' not found

### ISSUE THREAD

**Issue by digram** [spatie/laravel-image-optimizer#24]
Hi. I deleted this package from composer.json then ran the command composer update but ended up getting this error: 

[Symfony\Component\Debug\Exception\FatalThrowableError]   Class 'Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider' not found [Symfony\Component\Debug\Exception\FatalThrowableError]   Class 'Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by freekmurze** [comment]
I'm guessing this is caused by the auto discovery feature of Laravel 5.5

Could you try deleting `bootstrap/cache/packages.php` and try again? Does the problem persist?

**Comment by digram** [comment]
I'm using Laravel 5.4.36 and your solution worked after i deleted config.php and services.php from bootstrap/cache folder. I then ran php artisan config:cache command and new ones were created. Thanks for the solution.
