### ISSUE TITLE
array upload error

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-image-optimizer#25]
> Type error: Argument 1 passed to Spatie\LaravelImageOptimizer\Middlewares\OptimizeImages::Spatie\LaravelImageOptimizer\Middlewares\{closure}() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, array given

![screen shot 2017-09-01 at 1 53 09 pm](https://user-images.githubusercontent.com/7388088/29968762-6af1b832-8f1d-11e7-8dab-2ee3d4e2a75b.jpg)

https://github.com/spatie/laravel-image-optimizer/blob/5a12035a33fac5d3916bd7c8a5f1a3a69e4382be/src/Middlewares/OptimizeImages.php#L15

problem related to `UploadedFile $file` as it accept an object not array

https://github.com/spatie/laravel-image-optimizer/pull/26

**Comment by freekmurze** [comment]
We'll handle this in #25
