### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by itarafath** [spatie/laravel-image-optimizer#28]
throw error.
`(1/1) FatalThrowableError
Class 'ImageOptimizer' not found`

**Comment by freekmurze** [comment]
Verify that you've followed all install steps. When using the facade don't forget to import the `ImageOptimizer` namespace.

**Comment by itarafath** [comment]
Yes. I import the class and follow the steps.below is my code
<?php

namespace App\Http\Controllers;

use ImageOptimizer;

class TestController extends Controller
{
    function imageCompress()
    {
        $dir = __DIR__ . '/../../../public/compress/';
        $pathToImage = $dir . 'pexels-photo-392748.jpeg';
        $pathToOptimizedImage = $dir . 'compress-pexels-photo-395196.jpeg';

        ImageOptimizer::optimize($pathToImage);
        ImageOptimizer::optimize($pathToImage, $pathToOptimizedImage);
    }
}

**Comment by gidomanders** [comment]
Found the solution! In the readme it says you have to do:
```
php artisan vendor:publish --provider="Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider"
```

After that, something the readme doesn't explain, edit your config/app.php to add the service provider:
```
    'providers' => [
        ...

        /*
         * Package Service Providers...
         */
        ...
        Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider::class,

        ...
    ],
```

And then
```php artisan config:clear && php artisan optimize```

**Comment by pakcybershagufta** [comment]
UNable to publish in laravel 5.7
