### ISSUE TITLE
jpegoptim don't recognized as an internal or external command

### ISSUE THREAD

**Issue by soyjonathanespinosa** [spatie/laravel-image-optimizer#31]
I'm trying to use this package, but in the logs is giving me: "jpegoptim don't recognized as an internal or external command" and is not working.

I hope you can help me.

Thank you

**Comment by freekmurze** [comment]
Is `jpegoptim` installed on your system?

**Comment by soyjonathanespinosa** [comment]
I dont know, How can I install it? 

Sorry.

**Comment by freekmurze** [comment]
https://www.linuxhelp.com/install-jpegoptim-optipng-linux/

**Comment by bhargavkaklotara** [comment]
`public function getCommand(): string
    {
        $optionString = implode(' ', $this->options);

        return "{$this->binaryName} {$optionString} ".escapeshellarg($this->imagePath);
    }`

change getCommand() functoin like this in 

BaseOptimier.php located at "path-to-your-project\vendor\spatie\image-optimizer\src\Optimizers\BaseOptimizer.php"
