### ISSUE TITLE
Images sizes don't change

### ISSUE THREAD

**Issue by hsntngr55** [spatie/laravel-image-optimizer#34]
Images size nothing changed. Where do I mistake ? My laravel version is 5.5

use Spatie\LaravelImageOptimizer\Facades\ImageOptimizer;
`
public function store(Request $request){

 foreach ($request->images as $image){

     $media = new Media;

     $file = $image;

     $image_name = time()."-".$image->getClientOriginalName();

     $path = $file->move('uploads',$image_name);

     if ($request->has('optimize')) {
         ImageOptimizer::optimize($path);
     }

     if (!$request->has('noresize')) {
         Image::make(sprintf('uploads/%s', $image_name))->resize(640, 409)->save();
     }

     $media->image = $image_name;

     $media->save();
 }

 return back();

}
'

**Comment by freekmurze** [comment]
You probably didn't install the tools mentioned in the readme: https://github.com/spatie/laravel-responsecache#csrf-tokens

Install them, and try again.
