### ISSUE TITLE
I tested it with gtmetrix and it says that image can still be reduced.

### ISSUE THREAD

**Issue by jericopulvera** [spatie/laravel-image-optimizer#35]
Anyone got a custom optimizer for maximum lossless compression?

**Comment by sebastiandedeyne** [comment]
What tools could/should be added to improve the compression?

**Comment by TheBigK** [comment]
Cool. I came here looking for the same issue. Is there a setting we could tweak that allows us to determine how much compression is applied?

I think the setting `Jpegoptim::class => [-m85', // set maximum quality to 85%]` applies only to the Jpegoptim. Most of the image I have are PNG.

**Comment by freekmurze** [comment]
You should research and tweak the options of the various tools yourself. Closing this issue for now. If you have a good suggestion for the maximum compressions feel free to comment below.
