### ISSUE TITLE
Error: "Array to string conversion" after composer update

### ISSUE THREAD

**Issue by mssmaks** [spatie/laravel-image-optimizer#38]
After today's dependency update, the optimizer stopped working. Gives an error message: Array to string conversion. The problem is due to the update of the symfony. When you return the previous version of the symfony, then everything works.
After these updates, the error went:
![symfonyupdate](https://user-images.githubusercontent.com/12599112/34082885-75ca42d2-e36f-11e7-9cd3-9e2b64ac61ce.PNG)
Error:
![error2](https://user-images.githubusercontent.com/12599112/34082929-fb7bc144-e36f-11e7-85a4-25e413f9598f.PNG)
File logs:
[ERROR.txt](https://github.com/spatie/laravel-image-optimizer/files/1565959/ERROR.txt)

**Comment by freekmurze** [comment]
I can't seem to reproduce this. Tests are running fine after running `composer update`. Is this still causing problems for you? Could you PR a failing test for me to check?

**Comment by mssmaks** [comment]
Just tried again. The error is still the same. Even tried to delete folders from the vendor, nothing.

**Comment by freekmurze** [comment]
The error is caused by symfony. They fixed it today: https://github.com/symfony/symfony/pull/25559

Probably a new version isn't tagged yet. Try running `composer update` in a few days.
