### ISSUE TITLE
is it possible to optimize an image on cloud disk ?

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-image-optimizer#40]
in the docs it says we just need the path
```php
app(Spatie\ImageOptimizer\OptimizerChain::class)->optimize($pathToImage);
```

which works perfectly on local, but on cloud am not sure how, do we feed it the url ?

**Comment by freekmurze** [comment]
This package only supports local file. 

If you want to optimize a file on remote filesystem you'll need to take care of the download yourself.
