### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by blu94** [spatie/laravel-image-optimizer#42]
The image didn't being compress after upload, the code are apply follow the readme, using laravel 5.5

**Comment by freekmurze** [comment]
Are you sure the correct binaries are installed on your system. Does your PHP installation have the right permissions to call them?

**Comment by khoiwalvikram2** [comment]
i have a same issue

**Comment by xiebruce** [comment]
same, but I've echo the command and manually executed it, actually it works, but not woking in php, and no error. BTW, where can I find the log?

**Comment by sfdsfdsfdesfdsghefasefs** [comment]
same issue man 
please help us...
