### ISSUE TITLE
Class 'ImageOptimizer' not found

### ISSUE THREAD

**Issue by umairali** [spatie/laravel-image-optimizer#43]
I am doing same like this but I am facing this error Class 'ImageOptimizer' not found

`use ImageOptimizer;
ImageOptimizer::optimize($pathToImage);`

I added Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider::class, in providers in app.php and run this command 

`php artisan vendor:publish --provider="Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider"`

**Comment by freekmurze** [comment]
Try running `php artisan config:clear`.

**Comment by umairali** [comment]
I added below line in aliases no it's not showing any error but the image is same no optimization apply to the image and not showing any error message.

`'ImageOptimizer' => Spatie\LaravelImageOptimizer\Facades\ImageOptimizer::class,`

**Comment by freekmurze** [comment]
Are you sure these tools are installed on your system?
https://github.com/spatie/image-optimizer#optimization-tools

You could set some `dd` statements in the various classes of this package to know what is going on or you could try [logging what this package does](https://github.com/spatie/image-optimizer#logging-the-optimization-process) to get to the root of the problem.

**Comment by umairali** [comment]
thank you

**Comment by billpebert** [comment]
> Are you sure these tools are installed on your system?
> https://github.com/spatie/image-optimizer#optimization-tools
> 
> You could set some `dd` statements in the various classes of this package to know what is going on or you could try [logging what this package does](https://github.com/spatie/image-optimizer#logging-the-optimization-process) to get to the root of the problem.

Hello sir, i also got this message: Class 'Spatie\ImageOptimizer' not found. (On windows 10)
I've installed the package.
