### ISSUE TITLE
No changes to image in Laravel 5.6

### ISSUE THREAD

**Issue by josephadah** [spatie/laravel-image-optimizer#45]
I followed the instruction and install the package, I ensure that all the optimization tools were installed properly on my machine, Yet the image remain unchanged after optimizing. 
What could be the problem. 
Here is my code.
`<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use ImageOptimizer;

class UserAvatarController extends Controller
{
    public function store()
    {
    	request()->validate([
    		'avatar' => 'required | image'
    	]);

    	ImageOptimizer::optimize(request()->file('avatar'));

    	auth()->user()->update([
    		'avatar_path' => request()->file('avatar')->store('images/avatars', 'public')
    	]);
    }
}`

**Comment by freekmurze** [comment]
Maybe your PHP installation does not have permission to execute binaries? Put a dd statement somewhere around where the binaries are actually called to find out.

**Comment by kneeki** [comment]
I too am not having any image optimization when using Laravel v5.6 and optimizeImages in a middleware. Users can upload images without error however the image size is not reduced at all. Above you mentioned that PHP may not have permission to execute binaries, how can I find that out?

Here's what I have going on: Kernel.php
```php
protected $routeMiddleware = [
   // ...
    'optimizeImages' => \Spatie\LaravelImageOptimizer\Middlewares\OptimizeImages::class,
];
```
api.php
```php
Route::middleware('auth')->group(function () {
    Route::middleware('optimizeImages')->group(function () {
        Route::post('user/avatar', 'Auth\UserController@uploadImage');
    });
});
```
UserController.php
```php
public function uploadImage(Request $request)
{
    $user = Auth::user();
    $path = $request->file('file')->store('avatars');

    $user->image = $path;
    $user->touch();
    $user->save();

    return $path;
}
```

**Comment by smchae** [comment]
@kneeki Did you install necessary tools? 
https://github.com/spatie/image-optimizer#optimization-tools
