### ISSUE TITLE
Laravel 5.4 support?

### ISSUE THREAD

**Issue by ferris-bane** [spatie/laravel-image-optimizer#46]
Hi, would there be any chance to add Laravel 5.4/PHP 5.6 support?

Unless there is any reason to force the package to php 7, I think it would be very useful for existing projects/servers that only have PHP 5.6.

**Comment by freekmurze** [comment]
We don't use those versions anymore. Feel free to invest your time in forking our code and maintaing a PHP 5.6 compatible version.
