### ISSUE TITLE
custom commands path

### ISSUE THREAD

**Issue by fatonsopa** [spatie/laravel-image-optimizer#48]
It seems like the package cannot execute commands if optimized packages are installed in path /usr/local/bin/*

I know I can create symlinks to this path, but in an online environment, it was supposed to work with a custom path.

Question:
can we set a custom binary name of a command. ex. from "jpegoptim" to "/usr/local/bin/jpegoptim"

Thank you,
Faton

**Comment by freekmurze** [comment]
Well handle this in your PR.
