### ISSUE TITLE
Call to undefined method Spatie\ImageOptimizer\Optimizers\Pngquant::setBinaryPath()

### ISSUE THREAD

**Issue by kamerk22** [spatie/laravel-image-optimizer#54]
Laravel 5.6 when setting `binary_path` in the config file I'm getting following error

`Call to undefined method Spatie\ImageOptimizer\Optimizers\Pngquant::setBinaryPath()`

**Comment by freekmurze** [comment]
This is fixed in the latest release. Run `composer update` to pull it in.

**Comment by kamerk22** [comment]
@freekmurze Thank you

**Comment by zeroiszero** [comment]
Hi, may i know how to set the binary path ? I am using it locally with xampp to try
