### ISSUE TITLE
Issue optimising images on CDN's

### ISSUE THREAD

**Issue by sdeering** [spatie/laravel-image-optimizer#55]
Hi guys, does optimize() work for images hosted on CDN's?

ie - we upload the image to the CDN and then optimise it?

```
Storage::put($path, (string) $image, 'public');
ImageOptimizer::optimize($path);
```

Only other way around it i can think of is to store the image to local disk, then optimise it, then upload it to CDN and then remove local image.

**Comment by freekmurze** [comment]
This package only operates on local files.
