### ISSUE TITLE
Adding Laravel 5.7 support deletes all illuminate/* packages

### ISSUE THREAD

**Issue by Leeloo5E** [spatie/laravel-image-optimizer#58]
With the update from 1.3.1 to 1.3.2 there was added Laravel 5.7.0 support. 

This is great, but there was a problem while adding

`"laravel/framework": "~5.5.0|~5.6.0|~5.7.0",`

as requirement in spatie/laravel-image-optimizer 's composer.json. Before it was

`"illuminate/support": "~5.5.0|~5.6.0",`

Now the whole Laravel-Framework where added to our project. But our project is using the Lumen-Framework in Version 5.5. With the change and the update, all of the "illuminate/*" packages where deleted from the project.

Is it possible to use

`"illuminate/support": "~5.5.0|~5.6.0|~5.7.0",`

instead?

**Comment by freekmurze** [comment]
We accept a PR that changes this.
