### ISSUE TITLE
how to install optimization binaries in windows

### ISSUE THREAD

**Issue by haseeb-catalyst** [spatie/laravel-image-optimizer#62]

**Comment by repat** [comment]
```
$ choco install jpegoptim optipng pngquant gifsicle
$ npm install -g svgo
```

haven't tried it but should work

**Comment by atymic** [comment]
@haseeb-catalyst 
Did you manage to solve the issue?

**Comment by prateekvarma** [comment]
I have the same question.

**Comment by atymic** [comment]
@prateekvarma did you try the answer above?

**Comment by prateekvarma** [comment]
@atymic 

Failures
 - jpegoptim - jpegoptim not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.

**Comment by freekmurze** [comment]
This error is not related to our package. Please find good instructions on how to install the binary on your specifix system.
