### ISSUE TITLE
installing optimization tools

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-image-optimizer#73]
Hi,

Based on this document [here](https://github.com/spatie/image-optimizer#optimization-tools) I need to install some extra packages in order to get this package to work.

The document above mentioned installation on `linux` and `macOS` but hold on a sec! I have plan to run my app on shared hosting not local computers what now? should i still install some packages there?

> PS: unlike VPS and Clouds, shared hosting doesn't allow you to install everything you want.

### Question

Will this package work after i uploaded my application on hosting or should I just forget about it?

**Comment by atymic** [comment]
The chances of it working on shared hosting are very slim. You could email the list of requirements to the host and ask, but I doubt they are available.

**Comment by agharium** [comment]
I ran into the same issue. What I did was using a javascript tool to compress the image before uploading it as a blob file and afterwards converting it to an actual image on the Laravel controller.

https://github.com/Donaldcwl/browser-image-compression works pretty nicely.

Altough I miss the ease of Laravel Image Optimizer :/
