### ISSUE TITLE
Is there any way to optimize all the images in filesystem?

### ISSUE THREAD

**Issue by bhaswanth97** [spatie/laravel-image-optimizer#74]
I am using this package in my project to optimize uploaded images. I am very much happy with the package since it is working fine with all my uploaded images. But the problem is, I started to use the package in the middle of the project, so there are so many images already uploaded to the filesystem before using the package. So I wonder if there is any way to optimize all the images from the filesystem automatically? Any help regarding this issue will be appreciated. Thank you.

**Comment by freekmurze** [comment]
This question is a bit out of scope for this package.

I guess you'll need to download all non-optimized images, optimize them and upload them again.

**Comment by bhaswanth97** [comment]
Okay, Thanks for the reply.
