### ISSUE TITLE
Doesn't works on Laravel 6

### ISSUE THREAD

**Issue by ycruzb** [spatie/laravel-image-optimizer#77]
I've done all steps on the documentation and don't get errors but there is no optimization process on the uploaded images.

Can you help please ?

**Comment by nevadskiy** [comment]
@ycruzb Hi!

Make sure you have installed all required [tools](https://github.com/spatie/image-optimizer#optimization-tools) on your machine.

**Comment by ycruzb** [comment]
@nevadskiy you're right, it must be the cause. I've finally used http://resmush.it/ and it works pretty well.
