### ISSUE TITLE
laravel 6 issue install 

### ISSUE THREAD

**Issue by netstreet** [spatie/laravel-image-optimizer#79]
system lasted laravel 6
php 7.4.1
nginx

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing spatie/image-optimizer (1.2.1): Loading from cache
  - Installing spatie/laravel-image-optimizer (1.5.1): Loading from cache

> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Spatie\LaravelImageOptimizer\OptimizerChainFactory::create() must be of the type array, null given, called in

**Comment by rmiqbalramadhan** [comment]
After run composer require, i get this error. CMIIW.

Using version ^1.5 for spatie/laravel-image-optimizer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.3.0
    - Conclusion: don't install laravel/framework v6.3.0
    - madnest/madzipper v1.0.0 requires illuminate/filesystem 5.8 - 6.0 -> satisfiable by laravel/framework[5.8.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4], illuminate/filesystem[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - madnest/madzipper v1.0.1 requires illuminate/filesystem 5.8 - 6.0 -> satisfiable by laravel/framework[5.8.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4], illuminate/filesystem[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.3.0].
    - Can only install one of: laravel/framework[v6.0.0, v6.3.0].
    - Can only install one of: laravel/framework[v6.0.1, v6.3.0].
    - Can only install one of: laravel/framework[v6.0.2, v6.3.0].
    - Can only install one of: laravel/framework[v6.0.3, v6.3.0].
    - Can only install one of: laravel/framework[v6.0.4, v6.3.0].
    - don't install illuminate/filesystem 5.8.x-dev|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.0|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.11|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.12|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.14|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.15|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.17|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.18|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.19|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.2|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.20|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.22|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.24|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.27|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.28|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.29|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.3|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.30|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.31|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.32|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.33|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.34|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.35|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.36|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.4|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.8|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v5.8.9|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v6.0.0|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v6.0.1|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v6.0.2|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v6.0.3|don't install laravel/framework v6.3.0
    - don't install illuminate/filesystem v6.0.4|don't install laravel/framework v6.3.0
    - Installation request for laravel/framework (locked at v6.3.0, required as ^6.0) -> satisfiable by laravel/framework[v6.3.0].
    - Installation request for madnest/madzipper 1.0.x -> satisfiable by madnest/madzipper[v1.0.0, v1.0.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
According to our tests, the package is working as intended.

Please execute `php artisan cache:clear` to make sure the config is loaded.

If the problem persist after that, please PR a failing test for us to fix.

**Comment by rmiqbalramadhan** [comment]
Yep, I did downgrade my laravel\framework from composer.lock version 6.3.0 to 6.0.4 which can be satisfied by this package. Thank you spatie dev.
