### ISSUE TITLE
Image not resize

### ISSUE THREAD

**Issue by amasahara** [spatie/laravel-image-optimizer#80]
i has been install by 
composer require spatie/laravel-image-optimizer

and publishing the config file
php artisan vendor:publish --provider="Spatie\LaravelImageOptimizer\ImageOptimizerServiceProvider"

but when i use it
 Storage::putFileAs('public/books', $request->file('image'), $fileName);
 ImageOptimizer::optimize(storage_path('app/public/books/' . $fileName));

which way i wrong

**Comment by rmmaitrey9** [comment]
For me also it is same. I am using Laravel 6, spatie/image-optimizer 1.2 and spatie/laravel-image-optimizer 1.6. Also I have installed all the required tools mentioned [here](https://github.com/spatie/image-optimizer#optimization-tools) on my macos.

Still image size is not getting reduced. Can anyone help here ?

**Comment by omaritoml** [comment]
Same problem here, Laravel 7. Image not resizing.

**Comment by Fredwared** [comment]
This package does not include resize feature. You have to use another package e.g http://image.intervention.io/

**Comment by afrazahmmad** [comment]
in config/image-optimizer/ file
log_optimizer_activity => true,
to enable logs

then logs showed that some commands could not be run becuase below libraries were missing.
 
pngquant
optipng
jpegoptim

After installing them image were optimized amazingly.
On server I did 
apt-get install pngquant etc
