### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by Seeman13** [spatie/laravel-image-optimizer#81]
Hello! I try use You package for optimistion images jpg.
Version Laravel: 5.8.
I Downloaded binary file here: http://freecode.com/projects/jpegoptim
File jpegoptim.exe in root disk C.
Command "C:\jpegoptim.exe --help" show: jpegoptim v1.3.0  Copyright (c) Timo Kokkonen, 1996-2013 e.t.c....
In config: /image-optimizer.php it: 'binary_path' => 'C:/jpegoptim.exe',

I Run script: ImageOptimizer::optimize($pathToImage, $pathToOptimizedImage);
In output I got original image without change and optimisation.

**Comment by rmiqbalramadhan** [comment]
i somehow got same issues. both size and resolution aren't changing. please provide more about the step by step of using this packge. Thank you.

**Comment by jartaud** [comment]
@Seeman13 You have to set the path to the binaries not the binaries themselves:

https://github.com/spatie/laravel-image-optimizer/issues/62#issuecomment-469358960
> choco install optipng pngquant gifsicle
> $ npm install -g svgo

https://versaweb.dl.sourceforge.net/project/jpegoptim/jpegoptim/jpegoptim-1.3.0-win32/jpegoptim-1.3.0-win32-binary.zip **to install jpegoptim**

```
image-optimizer.php
...
'binary_path' => env('IMG_OPTIMIZER_BIN_PATH', ''),
'log_optimizer_activity' => env('IMG_OPTIMIZER_LOG_ACTIVITY', false),

.env
IMG_OPTIMIZER_BIN_PATH='""C:\ProgramData\chocolatey\bin""'
IMG_OPTIMIZER_LOG_ACTIVITY=true
```

**Comment by Seeman13** [comment]
Thanks You for your answer! I'll understood! Thanks!
