### ISSUE TITLE
Dose not work for .jpeg

### ISSUE THREAD

**Issue by AbdullaevTimur** [spatie/laravel-image-optimizer#89]
I installed all the packages and write log to "Laravel log".
I catched this: `[2020-08-22 14:51:50] laravel.INFO: Process successfully ended with output /var/www/www-root/data/www/api.placehot.app/storage/app/public/places/4DSU4ZeDGwIuwwABNPBWz1cMBgB488VTVJeadpos.jpeg_compress 599x400 24bit P JFIF  [OK] 15369 --> 15369 bytes (0.00%), skipped.`.

For testing I rewrite .config to 25% quality. But there are no effect on compression. 
Also, I have the same with  **spatie / image-optimizer** package.

**Comment by Dwingloo** [comment]
I have the same issue, tested it, doesn't work on .jpeg images, any fix?

**Comment by Dwingloo** [comment]
in fact its not working also on any other image extensions .jpg, .png, .svg...

**Comment by Dwingloo** [comment]
I just tried and tested it, wasn't working for any type of images, but after a little digging, I had to install the optimizers on the system first before getting it to work, dropped the package to be honest cause it will cause me trouble if shared hosting, went for TinyPNG API instead.
