### ISSUE TITLE
Optimize image uploaded via API/AJAX

### ISSUE THREAD

**Issue by felix2056** [spatie/laravel-image-optimizer#95]
The routing middleware does not support AJAX image upload.
Using the facade directly gives this error response:

```
"message": "`public/images/1601543257_test.jpg` does not exist",
"exception": "InvalidArgumentException",
"file": "C:\\xampp\\htdocs\\animecomm\\vendor\\spatie\\image-optimizer\\src\\Image.php",
```

Here are my codes
```
$file = $request->file('image');

$filename = time() . '_' . $file->getClientOriginalName();
$path = $file->storeAs('public/images/', $filename);
ImageOptimizer::optimize($path);
```

**Comment by freekmurze** [comment]
I've not encountered this problem myself before. Feel free to PR a fix for this, make sure to include tests.

**Comment by ahallhognason** [comment]
I was able to produce the same error and found the solution is to wrap the `$path` variable in a call to `Storage::path()`, like so:

```php
Route::post('/test-upload', function(Request $request){
	$file = $request->file('image');

	$filename = time() . '_' . $file->getClientOriginalName();
	$path = $file->storeAs('public/images/', $filename);
	ImageOptimizer::optimize(Storage::path($path));
});
```

**Comment by felix2056** [comment]
> I was able to produce the same error and found the solution is to wrap the `$path` variable in a call to `Storage::path()`, like so:
> 
> ```
> Route::post('/test-upload', function(Request $request){
> 	$file = $request->file('image');
> 
> 	$filename = time() . '_' . $file->getClientOriginalName();
> 	$path = $file->storeAs('public/images/', $filename);
> 	ImageOptimizer::optimize(Storage::path($path));
> });
> ```

Yes, this works thanks @ahallhognason
