### ISSUE TITLE
Not work in Laravel 8.9

### ISSUE THREAD

**Issue by dhavaldav** [spatie/laravel-image-optimizer#98]
It doesn't work in laravel 8.9
I didn't get any error but the image's file size didn't change.
Filesize: 1.2 MB 
Output Filesize:1.2 MB (same size as output )

Also, I have added this binaries on MacOS (https://github.com/spatie/image-optimizer#optimization-tools)

brew install jpegoptim
brew install optipng
brew install pngquant
brew install svgo
brew install gifsicle
brew install webp

**Comment by diego-lipinski-de-castro** [comment]
Same here, tried on docker
